permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Since when
  email: 838348914@qq.com
  link: http://anfishstory.com
  weibo: http://weibo.com/711231978
  github: http://github.com/fishstory1
  music: http://site.douban.com/gitbim/
  linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: Since When
description: a blog
url: http://anfishstory.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer5.png
favicon: /public/img/deer5.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com

# disqus 设置
disqus:
  shortname: anfishstory

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
